title: Yu Luo Learn German Meschen
description: Just notes I take when learning German 
remote_theme: just-the-docs/just-the-docs

url: https://ericluoyuu.github.io/Learn_German/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
plugins:
  - jekyll-remote-theme
